server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    username: smart_mine
    url: jdbc:mysql://43.138.242.246:3306/smart_mine?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimeZone=Asia/Shanghai
    password: nGEwSpjEPL7Ajnzi
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB     #上传文件大小限制
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.smart_admin.domain
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #输出sql语句
pagehelper:
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致


