server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    url: jdbc:mysql://43.138.242.246:3306/smart_mine?serverTimezone=Asia/Shanghai&useSSL=false
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.smart_admin.domain
pagehelper:
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致

