server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    username: smart_mine
    url: jdbc:mysql://43.138.242.246:3306/smart_mine?serverTimezone=Asia/Shanghai
    password: nGEwSpjEPL7Ajnzi
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.smart_admin.domain
pagehelper:
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致

